/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinTest

/**
 * This is how a test should look like. Need to figure out
 * how to instantiate the PApplet and then test the
 * librarie's methods.
 */
class HelloLibrary1Test {
    @org.junit.Test
    fun isAvailableMethodReturnsTrue() {
        //val pApplet = PApplet()
        //val classUnderTest = SomeP5Library(pApplet)

        //assertTrue(classUnderTest.isAvailable(),
        //    ".isAvailable() should return 'true'")

        //classUnderTest.someMethod(1, 2, 3, 4)

        //assertTrue(classUnderTest.VERSION == "0.2.4", "version seems right")
    }
}
